---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1fgnsprwxf64glzmj47kwgfsesmetjt5jy7djtdn2e0u2mk6wkggs7n0yl6"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1fgnsprwxf64glzmj47kwgfsesmetjt5jy7djtdn2e0u2mk6wkggs7n0yl6"
stores:
  yaml:
    indent: 2
