# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:U/A0Dw2DvSK7Yb941ytB1k194aH/IzVut49pdWZE25BlatGMDn6Ri827ww/PW+gPrzP6nx7SPywTHMywGZ+wg55qgOBeEUZhXq0+cJhgXLWxuHFOgAmxUyNZEqOcBm/iMJn6rB5CyHK7byaMalClRtmudoixaDYXOGOgc6YD2GDIVMDlvgpjc+zf1Kspf/Emh/ZsrVLjQ/dkPwmSCP4dFKC7SNfc0Ck42mbBmRWV+6DaHZgh,iv:UACy6gd0DPYYjpXbuVRSDKiwmsDdea8uhsHxhaqIGAo=,tag:WGuOZ/U9Gk28WkPtKKjFzg==,type:str]
sops:
  age:
    - recipient: age1fgnsprwxf64glzmj47kwgfsesmetjt5jy7djtdn2e0u2mk6wkggs7n0yl6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SnZJU1IwWDhzVzcwZStq
        TnFxaTJXRXlJSUtCSlo5UlU3WnVpZFZuUjI0CjJnN2tLUEk5SFBzM25qN1hkTW9j
        UW9qWFhBajFpcXpvN2pzTk15bDdVNU0KLS0tIHE3Z3RTMS92dGtkbXpQNDd5QXJC
        U2NwRE45a1hrTzdrRjQvTWxFNEU5SUEKyzfm3Yi39Y6f1G+Wqnj9CiVBhfE3KqTN
        XUQJLEKS56QSmlE1CnkDy8QB6nGXHfsaqCetaswsr5Zxdr3Q3FMGDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T09:48:19Z"
  mac: ENC[AES256_GCM,data:dGsoQdpxZXdnFAgUhpmGv6po5GJ5cpQceiEJer0j98EaR7moWcZ6VzSEUOxvEw2/gm/5/5N7g90T9Y68b4vPbXhcOZaRv4Hw6WlGH35Fy64IobHyuwe/h91cvPUFtupHD9e9ixib06KOkm5mJW7e1UtvjXQGFwOk/Fd4QUl+RWY=,iv:ueX6VFBzb5+pcJcHT9XvgpXUKPRMc2z5g7K+wICowZI=,tag:8pidUZUa+7Y7lA01XtVsuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
