# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DTTFMtuOxKccgjHAa5UuDLsgLKsdd4SOI1YlnMIpilPcIT8uSsSKuQ==,iv:zMaAZOSXcqJ7fon//K5o5vAUZNtpgQw3rJb1lOxxsDE=,tag:2ccxY+TpR2cfCghs2z2MLA==,type:str]
sops:
  age:
    - recipient: age1fgnsprwxf64glzmj47kwgfsesmetjt5jy7djtdn2e0u2mk6wkggs7n0yl6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeW5VRHU4SFpVai95eThB
        UW5GRzZENXZZSDg3R3BTMFBRMGxJcjlsVFJjCkZkMGhnZldYUjl2bTdva2I5WkFH
        SFBiMHg3ZnlGdHl0QnFEcWJXSkczenMKLS0tIEprLzZZVUdEN0FiRERFNFIzbElI
        ZG9Tekh1M1FjM2I2dmRhY1REVHZweHcKS4UGbiL/d8lM1GIN6iw5RmtKHrGpE7af
        qP1a9lbv4b1DutUm0ZNMor79KAPdTZpcvbsI+qn5o8kiwShmu8mPHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T09:48:19Z"
  mac: ENC[AES256_GCM,data:96wYpMrng7Ry2VY1POpZIvLsU/kZwN+z1mwlFZ72LR/Y8nLgh/1Z/MuO93g5lF9Y5JWozkFQ1c0rqiiY0hDSe9vtaDlM+VIblRHkMAqZFnlUxxGWY6XSVQxAzEevv+71C2sSOs9jK5RVoNj/U+eQFOQ3Y2FfjPEFDvbqHm6ZigA=,iv:osggnloSwmTIeb5GYSjkrJtc9FQgggr1ihCXXQgQPAg=,tag:scldc8Iq6iKpxuohXFlIow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
