apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:2Pvkc/Zq8N6pOQ==,iv:8f+UC4yGL+654QjnqspGy179jy8q9WnpKz6XlzqZflA=,tag:XV3MaM2m+UpIxWOZU1g4GQ==,type:str]
sops:
  age:
    - recipient: age1fgnsprwxf64glzmj47kwgfsesmetjt5jy7djtdn2e0u2mk6wkggs7n0yl6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweFFpRUFGMVJSblc2SHk5
        N0NMSlVWSk1kSEtDTGZUZTZ5anlGdjI0aUVrCkwzRHZOekpHdUIxMVFBQkNoa05I
        RVJtVWFmV09PanNQeWIxZE9sd3M0MnMKLS0tIEM2MS95dUt3Q3Q0ZVBWTXFNTmlE
        V1lodkFYM0FUa1VzZHRiQVQxTnh1OXcKqxYXqD7XjgRGET/M3DZEZ333qhbI4jge
        FdgSRuC1i9syA82yDs1mX6S5eEy8WluShVRAO3zvfb7uJWVlE5LnfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-06T09:48:19Z"
  mac: ENC[AES256_GCM,data:s0eaAHcTB0mooP4H+79tgkSA6FPhMAtmZ4X7xd6cjSQa2mGrRHs1sfYExaRoNGKZOLdOzpc6FaeRGiSGqob4pRM7TKShRq2DolA7zU1HjgIZxwTLexxDgxILNkQ/fgthiPBL6Hll+3r14sN1pYAXpoWw1pFfZ1drlhEmuaGUzdE=,iv:LBF8EyVOm7dRjB+fzxWYtWX6T4MXzYJ3AEs3BKdkX3g=,tag:sDS8dpgAJ/oqcWvVuevMBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
